// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/event.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Kaname_V1_EventEnvelope: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var schemaVersion: Kaname_V1_SchemaVersion {
    get {_storage._schemaVersion ?? Kaname_V1_SchemaVersion()}
    set {_uniqueStorage()._schemaVersion = newValue}
  }
  /// Returns true if `schemaVersion` has been explicitly set.
  public var hasSchemaVersion: Bool {_storage._schemaVersion != nil}
  /// Clears the value of `schemaVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSchemaVersion() {_uniqueStorage()._schemaVersion = nil}

  public var eventID: String {
    get {_storage._eventID}
    set {_uniqueStorage()._eventID = newValue}
  }

  public var storePosition: UInt64 {
    get {_storage._storePosition}
    set {_uniqueStorage()._storePosition = newValue}
  }

  public var streamID: String {
    get {_storage._streamID}
    set {_uniqueStorage()._streamID = newValue}
  }

  public var streamSequence: UInt64 {
    get {_storage._streamSequence}
    set {_uniqueStorage()._streamSequence = newValue}
  }

  public var occurredAtUnixMillis: Int64 {
    get {_storage._occurredAtUnixMillis}
    set {_uniqueStorage()._occurredAtUnixMillis = newValue}
  }

  public var kind: String {
    get {_storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  public var payload: Kaname_V1_OpaqueTypedPayload {
    get {_storage._payload ?? Kaname_V1_OpaqueTypedPayload()}
    set {_uniqueStorage()._payload = newValue}
  }
  /// Returns true if `payload` has been explicitly set.
  public var hasPayload: Bool {_storage._payload != nil}
  /// Clears the value of `payload`. Subsequent reads from it will return its default value.
  public mutating func clearPayload() {_uniqueStorage()._payload = nil}

  public var provenance: Kaname_V1_EventProvenance {
    get {_storage._provenance ?? Kaname_V1_EventProvenance()}
    set {_uniqueStorage()._provenance = newValue}
  }
  /// Returns true if `provenance` has been explicitly set.
  public var hasProvenance: Bool {_storage._provenance != nil}
  /// Clears the value of `provenance`. Subsequent reads from it will return its default value.
  public mutating func clearProvenance() {_uniqueStorage()._provenance = nil}

  public var causationID: String {
    get {_storage._causationID}
    set {_uniqueStorage()._causationID = newValue}
  }

  public var correlationID: String {
    get {_storage._correlationID}
    set {_uniqueStorage()._correlationID = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Kaname_V1_RawEvidenceReference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var digest: String = String()

  public var byteCount: UInt64 = 0

  public var retentionClass: Kaname_V1_EvidenceRetentionClass = .unspecified

  public var expiresAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_EventEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EventEnvelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schema_version\0\u{3}event_id\0\u{3}store_position\0\u{3}stream_id\0\u{3}stream_sequence\0\u{3}occurred_at_unix_millis\0\u{1}kind\0\u{1}payload\0\u{1}provenance\0\u{3}causation_id\0\u{3}correlation_id\0\u{b}canonical_bytes\0\u{c}\u{c}\u{14}")

  fileprivate class _StorageClass {
    var _schemaVersion: Kaname_V1_SchemaVersion? = nil
    var _eventID: String = String()
    var _storePosition: UInt64 = 0
    var _streamID: String = String()
    var _streamSequence: UInt64 = 0
    var _occurredAtUnixMillis: Int64 = 0
    var _kind: String = String()
    var _payload: Kaname_V1_OpaqueTypedPayload? = nil
    var _provenance: Kaname_V1_EventProvenance? = nil
    var _causationID: String = String()
    var _correlationID: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _schemaVersion = source._schemaVersion
      _eventID = source._eventID
      _storePosition = source._storePosition
      _streamID = source._streamID
      _streamSequence = source._streamSequence
      _occurredAtUnixMillis = source._occurredAtUnixMillis
      _kind = source._kind
      _payload = source._payload
      _provenance = source._provenance
      _causationID = source._causationID
      _correlationID = source._correlationID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._schemaVersion) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._eventID) }()
        case 3: try { try decoder.decodeSingularUInt64Field(value: &_storage._storePosition) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._streamID) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._streamSequence) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._occurredAtUnixMillis) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._kind) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._payload) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._provenance) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._causationID) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._correlationID) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._schemaVersion {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._eventID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._eventID, fieldNumber: 2)
      }
      if _storage._storePosition != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._storePosition, fieldNumber: 3)
      }
      if !_storage._streamID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._streamID, fieldNumber: 4)
      }
      if _storage._streamSequence != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._streamSequence, fieldNumber: 5)
      }
      if _storage._occurredAtUnixMillis != 0 {
        try visitor.visitSingularInt64Field(value: _storage._occurredAtUnixMillis, fieldNumber: 6)
      }
      if !_storage._kind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._kind, fieldNumber: 7)
      }
      try { if let v = _storage._payload {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._provenance {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if !_storage._causationID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._causationID, fieldNumber: 10)
      }
      if !_storage._correlationID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._correlationID, fieldNumber: 11)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_EventEnvelope, rhs: Kaname_V1_EventEnvelope) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._schemaVersion != rhs_storage._schemaVersion {return false}
        if _storage._eventID != rhs_storage._eventID {return false}
        if _storage._storePosition != rhs_storage._storePosition {return false}
        if _storage._streamID != rhs_storage._streamID {return false}
        if _storage._streamSequence != rhs_storage._streamSequence {return false}
        if _storage._occurredAtUnixMillis != rhs_storage._occurredAtUnixMillis {return false}
        if _storage._kind != rhs_storage._kind {return false}
        if _storage._payload != rhs_storage._payload {return false}
        if _storage._provenance != rhs_storage._provenance {return false}
        if _storage._causationID != rhs_storage._causationID {return false}
        if _storage._correlationID != rhs_storage._correlationID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_RawEvidenceReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RawEvidenceReference"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}digest\0\u{3}byte_count\0\u{3}retention_class\0\u{3}expires_at_unix_millis\0\u{b}raw_data\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.digest) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.byteCount) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.retentionClass) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.expiresAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.digest.isEmpty {
      try visitor.visitSingularStringField(value: self.digest, fieldNumber: 1)
    }
    if self.byteCount != 0 {
      try visitor.visitSingularUInt64Field(value: self.byteCount, fieldNumber: 2)
    }
    if self.retentionClass != .unspecified {
      try visitor.visitSingularEnumField(value: self.retentionClass, fieldNumber: 3)
    }
    if self.expiresAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAtUnixMillis, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_RawEvidenceReference, rhs: Kaname_V1_RawEvidenceReference) -> Bool {
    if lhs.digest != rhs.digest {return false}
    if lhs.byteCount != rhs.byteCount {return false}
    if lhs.retentionClass != rhs.retentionClass {return false}
    if lhs.expiresAtUnixMillis != rhs.expiresAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
