// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/queue.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Kaname_V1_QueueReceiptState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case savedOnPhone // = 1
  case receivedByMac // = 2
  case policyAccepted // = 3
  case providerDispatchAccepted // = 4
  case runStarted // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .savedOnPhone
    case 2: self = .receivedByMac
    case 3: self = .policyAccepted
    case 4: self = .providerDispatchAccepted
    case 5: self = .runStarted
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .savedOnPhone: return 1
    case .receivedByMac: return 2
    case .policyAccepted: return 3
    case .providerDispatchAccepted: return 4
    case .runStarted: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_QueueReceiptState] = [
    .unspecified,
    .savedOnPhone,
    .receivedByMac,
    .policyAccepted,
    .providerDispatchAccepted,
    .runStarted,
  ]

}

public nonisolated struct Kaname_V1_QueueItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var itemID: String = String()

  public var streamID: String = String()

  public var revision: UInt64 = 0

  public var position: UInt64 = 0

  public var body: String = String()

  public var authorID: String = String()

  public var createdAtUnixMillis: Int64 = 0

  public var disposition: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_QueueEdit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var itemID: String = String()

  public var expectedRevision: UInt64 = 0

  public var body: String = String()

  public var actorID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_QueueReceipt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var itemID: String = String()

  public var state: Kaname_V1_QueueReceiptState = .unspecified

  public var revision: UInt64 = 0

  public var recordedAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_QueueReceiptState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0QUEUE_RECEIPT_STATE_UNSPECIFIED\0\u{1}QUEUE_RECEIPT_STATE_SAVED_ON_PHONE\0\u{1}QUEUE_RECEIPT_STATE_RECEIVED_BY_MAC\0\u{1}QUEUE_RECEIPT_STATE_POLICY_ACCEPTED\0\u{1}QUEUE_RECEIPT_STATE_PROVIDER_DISPATCH_ACCEPTED\0\u{1}QUEUE_RECEIPT_STATE_RUN_STARTED\0")
}

nonisolated extension Kaname_V1_QueueItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueueItem"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}item_id\0\u{3}stream_id\0\u{1}revision\0\u{1}position\0\u{1}body\0\u{3}author_id\0\u{3}created_at_unix_millis\0\u{1}disposition\0\u{c}\u{9}\u{7}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.itemID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.streamID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.revision) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.position) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.authorID) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.createdAtUnixMillis) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.disposition) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.itemID.isEmpty {
      try visitor.visitSingularStringField(value: self.itemID, fieldNumber: 1)
    }
    if !self.streamID.isEmpty {
      try visitor.visitSingularStringField(value: self.streamID, fieldNumber: 2)
    }
    if self.revision != 0 {
      try visitor.visitSingularUInt64Field(value: self.revision, fieldNumber: 3)
    }
    if self.position != 0 {
      try visitor.visitSingularUInt64Field(value: self.position, fieldNumber: 4)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 5)
    }
    if !self.authorID.isEmpty {
      try visitor.visitSingularStringField(value: self.authorID, fieldNumber: 6)
    }
    if self.createdAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAtUnixMillis, fieldNumber: 7)
    }
    if !self.disposition.isEmpty {
      try visitor.visitSingularStringField(value: self.disposition, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_QueueItem, rhs: Kaname_V1_QueueItem) -> Bool {
    if lhs.itemID != rhs.itemID {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs.revision != rhs.revision {return false}
    if lhs.position != rhs.position {return false}
    if lhs.body != rhs.body {return false}
    if lhs.authorID != rhs.authorID {return false}
    if lhs.createdAtUnixMillis != rhs.createdAtUnixMillis {return false}
    if lhs.disposition != rhs.disposition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_QueueEdit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueueEdit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}item_id\0\u{3}expected_revision\0\u{1}body\0\u{3}actor_id\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.itemID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.expectedRevision) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.actorID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.itemID.isEmpty {
      try visitor.visitSingularStringField(value: self.itemID, fieldNumber: 1)
    }
    if self.expectedRevision != 0 {
      try visitor.visitSingularUInt64Field(value: self.expectedRevision, fieldNumber: 2)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 3)
    }
    if !self.actorID.isEmpty {
      try visitor.visitSingularStringField(value: self.actorID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_QueueEdit, rhs: Kaname_V1_QueueEdit) -> Bool {
    if lhs.itemID != rhs.itemID {return false}
    if lhs.expectedRevision != rhs.expectedRevision {return false}
    if lhs.body != rhs.body {return false}
    if lhs.actorID != rhs.actorID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_QueueReceipt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueueReceipt"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}item_id\0\u{1}state\0\u{1}revision\0\u{3}recorded_at_unix_millis\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.itemID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.revision) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.recordedAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.itemID.isEmpty {
      try visitor.visitSingularStringField(value: self.itemID, fieldNumber: 1)
    }
    if self.state != .unspecified {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 2)
    }
    if self.revision != 0 {
      try visitor.visitSingularUInt64Field(value: self.revision, fieldNumber: 3)
    }
    if self.recordedAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.recordedAtUnixMillis, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_QueueReceipt, rhs: Kaname_V1_QueueReceipt) -> Bool {
    if lhs.itemID != rhs.itemID {return false}
    if lhs.state != rhs.state {return false}
    if lhs.revision != rhs.revision {return false}
    if lhs.recordedAtUnixMillis != rhs.recordedAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
