// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/notification.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Kaname_V1_AttentionRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var attentionID: String = String()

  public var streamID: String = String()

  public var kind: String = String()

  public var safePreviewClass: String = String()

  public var deepLinkTarget: String = String()

  public var expiresAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_NotificationReceipt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var attentionID: String = String()

  public var deliveryID: String = String()

  public var state: String = String()

  public var recordedAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_AttentionRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AttentionRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}attention_id\0\u{3}stream_id\0\u{1}kind\0\u{3}safe_preview_class\0\u{3}deep_link_target\0\u{3}expires_at_unix_millis\0\u{b}body\0\u{b}private_content\0\u{c}\u{7}\u{9}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.attentionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.streamID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.safePreviewClass) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.deepLinkTarget) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.expiresAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.attentionID.isEmpty {
      try visitor.visitSingularStringField(value: self.attentionID, fieldNumber: 1)
    }
    if !self.streamID.isEmpty {
      try visitor.visitSingularStringField(value: self.streamID, fieldNumber: 2)
    }
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 3)
    }
    if !self.safePreviewClass.isEmpty {
      try visitor.visitSingularStringField(value: self.safePreviewClass, fieldNumber: 4)
    }
    if !self.deepLinkTarget.isEmpty {
      try visitor.visitSingularStringField(value: self.deepLinkTarget, fieldNumber: 5)
    }
    if self.expiresAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAtUnixMillis, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_AttentionRecord, rhs: Kaname_V1_AttentionRecord) -> Bool {
    if lhs.attentionID != rhs.attentionID {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.safePreviewClass != rhs.safePreviewClass {return false}
    if lhs.deepLinkTarget != rhs.deepLinkTarget {return false}
    if lhs.expiresAtUnixMillis != rhs.expiresAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_NotificationReceipt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotificationReceipt"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}attention_id\0\u{3}delivery_id\0\u{1}state\0\u{3}recorded_at_unix_millis\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.attentionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deliveryID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.recordedAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.attentionID.isEmpty {
      try visitor.visitSingularStringField(value: self.attentionID, fieldNumber: 1)
    }
    if !self.deliveryID.isEmpty {
      try visitor.visitSingularStringField(value: self.deliveryID, fieldNumber: 2)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 3)
    }
    if self.recordedAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.recordedAtUnixMillis, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_NotificationReceipt, rhs: Kaname_V1_NotificationReceipt) -> Bool {
    if lhs.attentionID != rhs.attentionID {return false}
    if lhs.deliveryID != rhs.deliveryID {return false}
    if lhs.state != rhs.state {return false}
    if lhs.recordedAtUnixMillis != rhs.recordedAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
