// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/replay.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Kaname_V1_ReplayBasis: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case events // = 1
  case snapshot // = 2
  case resyncRequired // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .events
    case 2: self = .snapshot
    case 3: self = .resyncRequired
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .events: return 1
    case .snapshot: return 2
    case .resyncRequired: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_ReplayBasis] = [
    .unspecified,
    .events,
    .snapshot,
    .resyncRequired,
  ]

}

public nonisolated struct Kaname_V1_ReplayCursor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var selectorID: String = String()

  public var afterStorePosition: UInt64 = 0

  public var highWaterMark: UInt64 = 0

  public var retentionHorizon: UInt64 = 0

  public var integrityTag: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_ReplayRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var selectorID: String = String()

  public var cursor: Kaname_V1_ReplayCursor {
    get {_cursor ?? Kaname_V1_ReplayCursor()}
    set {_cursor = newValue}
  }
  /// Returns true if `cursor` has been explicitly set.
  public var hasCursor: Bool {self._cursor != nil}
  /// Clears the value of `cursor`. Subsequent reads from it will return its default value.
  public mutating func clearCursor() {self._cursor = nil}

  public var pageSize: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _cursor: Kaname_V1_ReplayCursor? = nil
}

public nonisolated struct Kaname_V1_SnapshotDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var snapshotID: String = String()

  public var selectorID: String = String()

  public var highWaterMark: UInt64 = 0

  public var checksum: Data = Data()

  public var projectionSchemaVersion: UInt32 = 0

  public var state: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_ReplayResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var basis: Kaname_V1_ReplayBasis = .unspecified

  public var snapshot: Kaname_V1_SnapshotDescriptor {
    get {_snapshot ?? Kaname_V1_SnapshotDescriptor()}
    set {_snapshot = newValue}
  }
  /// Returns true if `snapshot` has been explicitly set.
  public var hasSnapshot: Bool {self._snapshot != nil}
  /// Clears the value of `snapshot`. Subsequent reads from it will return its default value.
  public mutating func clearSnapshot() {self._snapshot = nil}

  public var events: [Kaname_V1_EventEnvelope] = []

  public var nextCursor: Kaname_V1_ReplayCursor {
    get {_nextCursor ?? Kaname_V1_ReplayCursor()}
    set {_nextCursor = newValue}
  }
  /// Returns true if `nextCursor` has been explicitly set.
  public var hasNextCursor: Bool {self._nextCursor != nil}
  /// Clears the value of `nextCursor`. Subsequent reads from it will return its default value.
  public mutating func clearNextCursor() {self._nextCursor = nil}

  public var highWaterMark: UInt64 = 0

  public var hasMore_p: Bool = false

  public var gapReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _snapshot: Kaname_V1_SnapshotDescriptor? = nil
  fileprivate var _nextCursor: Kaname_V1_ReplayCursor? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_ReplayBasis: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REPLAY_BASIS_UNSPECIFIED\0\u{1}REPLAY_BASIS_EVENTS\0\u{1}REPLAY_BASIS_SNAPSHOT\0\u{1}REPLAY_BASIS_RESYNC_REQUIRED\0")
}

nonisolated extension Kaname_V1_ReplayCursor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReplayCursor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}selector_id\0\u{3}after_store_position\0\u{3}high_water_mark\0\u{3}retention_horizon\0\u{3}integrity_tag\0\u{c}\u{6}\u{a}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.selectorID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.afterStorePosition) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.highWaterMark) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.retentionHorizon) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.integrityTag) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.selectorID.isEmpty {
      try visitor.visitSingularStringField(value: self.selectorID, fieldNumber: 1)
    }
    if self.afterStorePosition != 0 {
      try visitor.visitSingularUInt64Field(value: self.afterStorePosition, fieldNumber: 2)
    }
    if self.highWaterMark != 0 {
      try visitor.visitSingularUInt64Field(value: self.highWaterMark, fieldNumber: 3)
    }
    if self.retentionHorizon != 0 {
      try visitor.visitSingularUInt64Field(value: self.retentionHorizon, fieldNumber: 4)
    }
    if !self.integrityTag.isEmpty {
      try visitor.visitSingularBytesField(value: self.integrityTag, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_ReplayCursor, rhs: Kaname_V1_ReplayCursor) -> Bool {
    if lhs.selectorID != rhs.selectorID {return false}
    if lhs.afterStorePosition != rhs.afterStorePosition {return false}
    if lhs.highWaterMark != rhs.highWaterMark {return false}
    if lhs.retentionHorizon != rhs.retentionHorizon {return false}
    if lhs.integrityTag != rhs.integrityTag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_ReplayRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReplayRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}selector_id\0\u{1}cursor\0\u{3}page_size\0\u{c}\u{4}\u{c}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.selectorID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._cursor) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.pageSize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.selectorID.isEmpty {
      try visitor.visitSingularStringField(value: self.selectorID, fieldNumber: 1)
    }
    try { if let v = self._cursor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.pageSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.pageSize, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_ReplayRequest, rhs: Kaname_V1_ReplayRequest) -> Bool {
    if lhs.selectorID != rhs.selectorID {return false}
    if lhs._cursor != rhs._cursor {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_SnapshotDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SnapshotDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}snapshot_id\0\u{3}selector_id\0\u{3}high_water_mark\0\u{1}checksum\0\u{3}projection_schema_version\0\u{1}state\0\u{c}\u{7}\u{9}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.snapshotID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.selectorID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.highWaterMark) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.checksum) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.projectionSchemaVersion) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.state) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.snapshotID.isEmpty {
      try visitor.visitSingularStringField(value: self.snapshotID, fieldNumber: 1)
    }
    if !self.selectorID.isEmpty {
      try visitor.visitSingularStringField(value: self.selectorID, fieldNumber: 2)
    }
    if self.highWaterMark != 0 {
      try visitor.visitSingularUInt64Field(value: self.highWaterMark, fieldNumber: 3)
    }
    if !self.checksum.isEmpty {
      try visitor.visitSingularBytesField(value: self.checksum, fieldNumber: 4)
    }
    if self.projectionSchemaVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.projectionSchemaVersion, fieldNumber: 5)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularBytesField(value: self.state, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_SnapshotDescriptor, rhs: Kaname_V1_SnapshotDescriptor) -> Bool {
    if lhs.snapshotID != rhs.snapshotID {return false}
    if lhs.selectorID != rhs.selectorID {return false}
    if lhs.highWaterMark != rhs.highWaterMark {return false}
    if lhs.checksum != rhs.checksum {return false}
    if lhs.projectionSchemaVersion != rhs.projectionSchemaVersion {return false}
    if lhs.state != rhs.state {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_ReplayResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReplayResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}basis\0\u{1}snapshot\0\u{1}events\0\u{3}next_cursor\0\u{3}high_water_mark\0\u{3}has_more\0\u{3}gap_reason\0\u{c}\u{8}\u{8}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.basis) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._snapshot) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.events) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._nextCursor) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.highWaterMark) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.hasMore_p) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.gapReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.basis != .unspecified {
      try visitor.visitSingularEnumField(value: self.basis, fieldNumber: 1)
    }
    try { if let v = self._snapshot {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.events.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.events, fieldNumber: 3)
    }
    try { if let v = self._nextCursor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.highWaterMark != 0 {
      try visitor.visitSingularUInt64Field(value: self.highWaterMark, fieldNumber: 5)
    }
    if self.hasMore_p != false {
      try visitor.visitSingularBoolField(value: self.hasMore_p, fieldNumber: 6)
    }
    if !self.gapReason.isEmpty {
      try visitor.visitSingularStringField(value: self.gapReason, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_ReplayResponse, rhs: Kaname_V1_ReplayResponse) -> Bool {
    if lhs.basis != rhs.basis {return false}
    if lhs._snapshot != rhs._snapshot {return false}
    if lhs.events != rhs.events {return false}
    if lhs._nextCursor != rhs._nextCursor {return false}
    if lhs.highWaterMark != rhs.highWaterMark {return false}
    if lhs.hasMore_p != rhs.hasMore_p {return false}
    if lhs.gapReason != rhs.gapReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
