// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/command.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Kaname_V1_CommandDisposition: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case accepted // = 1
  case rejected // = 2
  case duplicate // = 3
  case conflict // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .accepted
    case 2: self = .rejected
    case 3: self = .duplicate
    case 4: self = .conflict
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .accepted: return 1
    case .rejected: return 2
    case .duplicate: return 3
    case .conflict: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_CommandDisposition] = [
    .unspecified,
    .accepted,
    .rejected,
    .duplicate,
    .conflict,
  ]

}

public nonisolated struct Kaname_V1_CommandEnvelope: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var schemaVersion: Kaname_V1_SchemaVersion {
    get {_storage._schemaVersion ?? Kaname_V1_SchemaVersion()}
    set {_uniqueStorage()._schemaVersion = newValue}
  }
  /// Returns true if `schemaVersion` has been explicitly set.
  public var hasSchemaVersion: Bool {_storage._schemaVersion != nil}
  /// Clears the value of `schemaVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSchemaVersion() {_uniqueStorage()._schemaVersion = nil}

  public var commandID: String {
    get {_storage._commandID}
    set {_uniqueStorage()._commandID = newValue}
  }

  public var idempotencyKey: String {
    get {_storage._idempotencyKey}
    set {_uniqueStorage()._idempotencyKey = newValue}
  }

  public var kind: String {
    get {_storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  public var payload: Kaname_V1_OpaqueTypedPayload {
    get {_storage._payload ?? Kaname_V1_OpaqueTypedPayload()}
    set {_uniqueStorage()._payload = newValue}
  }
  /// Returns true if `payload` has been explicitly set.
  public var hasPayload: Bool {_storage._payload != nil}
  /// Clears the value of `payload`. Subsequent reads from it will return its default value.
  public mutating func clearPayload() {_uniqueStorage()._payload = nil}

  public var scope: Kaname_V1_Scope {
    get {_storage._scope ?? Kaname_V1_Scope()}
    set {_uniqueStorage()._scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {_storage._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {_uniqueStorage()._scope = nil}

  public var actorID: String {
    get {_storage._actorID}
    set {_uniqueStorage()._actorID = newValue}
  }

  public var expectedRevision: UInt64 {
    get {_storage._expectedRevision}
    set {_uniqueStorage()._expectedRevision = newValue}
  }

  public var submittedAtUnixMillis: Int64 {
    get {_storage._submittedAtUnixMillis}
    set {_uniqueStorage()._submittedAtUnixMillis = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Kaname_V1_CommandOutcome: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var commandID: String = String()

  public var disposition: Kaname_V1_CommandDisposition = .unspecified

  public var reasonCode: String = String()

  public var storePosition: UInt64 = 0

  public var receiptID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_CommandDisposition: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COMMAND_DISPOSITION_UNSPECIFIED\0\u{1}COMMAND_DISPOSITION_ACCEPTED\0\u{1}COMMAND_DISPOSITION_REJECTED\0\u{1}COMMAND_DISPOSITION_DUPLICATE\0\u{1}COMMAND_DISPOSITION_CONFLICT\0")
}

nonisolated extension Kaname_V1_CommandEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommandEnvelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schema_version\0\u{3}command_id\0\u{3}idempotency_key\0\u{1}kind\0\u{1}payload\0\u{1}scope\0\u{3}actor_id\0\u{3}expected_revision\0\u{3}submitted_at_unix_millis\0\u{b}provider_token\0\u{b}secret\0\u{c}\u{a}\u{16}")

  fileprivate class _StorageClass {
    var _schemaVersion: Kaname_V1_SchemaVersion? = nil
    var _commandID: String = String()
    var _idempotencyKey: String = String()
    var _kind: String = String()
    var _payload: Kaname_V1_OpaqueTypedPayload? = nil
    var _scope: Kaname_V1_Scope? = nil
    var _actorID: String = String()
    var _expectedRevision: UInt64 = 0
    var _submittedAtUnixMillis: Int64 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _schemaVersion = source._schemaVersion
      _commandID = source._commandID
      _idempotencyKey = source._idempotencyKey
      _kind = source._kind
      _payload = source._payload
      _scope = source._scope
      _actorID = source._actorID
      _expectedRevision = source._expectedRevision
      _submittedAtUnixMillis = source._submittedAtUnixMillis
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._schemaVersion) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._commandID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._idempotencyKey) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._kind) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._payload) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._scope) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._actorID) }()
        case 8: try { try decoder.decodeSingularUInt64Field(value: &_storage._expectedRevision) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._submittedAtUnixMillis) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._schemaVersion {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._commandID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._commandID, fieldNumber: 2)
      }
      if !_storage._idempotencyKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._idempotencyKey, fieldNumber: 3)
      }
      if !_storage._kind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._kind, fieldNumber: 4)
      }
      try { if let v = _storage._payload {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._scope {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if !_storage._actorID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._actorID, fieldNumber: 7)
      }
      if _storage._expectedRevision != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._expectedRevision, fieldNumber: 8)
      }
      if _storage._submittedAtUnixMillis != 0 {
        try visitor.visitSingularInt64Field(value: _storage._submittedAtUnixMillis, fieldNumber: 9)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_CommandEnvelope, rhs: Kaname_V1_CommandEnvelope) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._schemaVersion != rhs_storage._schemaVersion {return false}
        if _storage._commandID != rhs_storage._commandID {return false}
        if _storage._idempotencyKey != rhs_storage._idempotencyKey {return false}
        if _storage._kind != rhs_storage._kind {return false}
        if _storage._payload != rhs_storage._payload {return false}
        if _storage._scope != rhs_storage._scope {return false}
        if _storage._actorID != rhs_storage._actorID {return false}
        if _storage._expectedRevision != rhs_storage._expectedRevision {return false}
        if _storage._submittedAtUnixMillis != rhs_storage._submittedAtUnixMillis {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_CommandOutcome: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommandOutcome"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}command_id\0\u{1}disposition\0\u{3}reason_code\0\u{3}store_position\0\u{3}receipt_id\0\u{c}\u{6}\u{a}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.commandID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.disposition) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.storePosition) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.receiptID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.commandID.isEmpty {
      try visitor.visitSingularStringField(value: self.commandID, fieldNumber: 1)
    }
    if self.disposition != .unspecified {
      try visitor.visitSingularEnumField(value: self.disposition, fieldNumber: 2)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 3)
    }
    if self.storePosition != 0 {
      try visitor.visitSingularUInt64Field(value: self.storePosition, fieldNumber: 4)
    }
    if !self.receiptID.isEmpty {
      try visitor.visitSingularStringField(value: self.receiptID, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_CommandOutcome, rhs: Kaname_V1_CommandOutcome) -> Bool {
    if lhs.commandID != rhs.commandID {return false}
    if lhs.disposition != rhs.disposition {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.storePosition != rhs.storePosition {return false}
    if lhs.receiptID != rhs.receiptID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
