// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Kaname_V1_EvidenceRetentionClass: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case none // = 1
  case sevenDays // = 2
  case scopedExtension // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .none
    case 2: self = .sevenDays
    case 3: self = .scopedExtension
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .none: return 1
    case .sevenDays: return 2
    case .scopedExtension: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_EvidenceRetentionClass] = [
    .unspecified,
    .none,
    .sevenDays,
    .scopedExtension,
  ]

}

/// Shared version information. A major change is never silently accepted.
public nonisolated struct Kaname_V1_SchemaVersion: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var major: UInt32 = 0

  public var minor: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A payload whose bytes are retained verbatim even when its type is unknown.
public nonisolated struct Kaname_V1_OpaqueTypedPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var typeURL: String = String()

  public var contentType: String = String()

  public var value: Data = Data()

  public var payloadVersion: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_EventProvenance: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sourceKind: String = String()

  public var providerInstanceID: String = String()

  public var nativeType: String = String()

  public var nativeCursor: Data = Data()

  public var rawEvidenceDigest: String = String()

  public var retentionClass: Kaname_V1_EvidenceRetentionClass = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_Scope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var projectID: String = String()

  public var workspaceID: String = String()

  public var accountID: String = String()

  public var authorityID: String = String()

  public var egressClass: String = String()

  public var destinationDigest: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_EvidenceRetentionClass: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EVIDENCE_RETENTION_CLASS_UNSPECIFIED\0\u{1}EVIDENCE_RETENTION_CLASS_NONE\0\u{1}EVIDENCE_RETENTION_CLASS_SEVEN_DAYS\0\u{1}EVIDENCE_RETENTION_CLASS_SCOPED_EXTENSION\0")
}

nonisolated extension Kaname_V1_SchemaVersion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SchemaVersion"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}major\0\u{1}minor\0\u{b}patch\0\u{c}\u{3}\u{d}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.major) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.minor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.major != 0 {
      try visitor.visitSingularUInt32Field(value: self.major, fieldNumber: 1)
    }
    if self.minor != 0 {
      try visitor.visitSingularUInt32Field(value: self.minor, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_SchemaVersion, rhs: Kaname_V1_SchemaVersion) -> Bool {
    if lhs.major != rhs.major {return false}
    if lhs.minor != rhs.minor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_OpaqueTypedPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OpaqueTypedPayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}type_url\0\u{3}content_type\0\u{1}value\0\u{3}payload_version\0\u{b}json_value\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.typeURL) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.value) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.payloadVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.typeURL.isEmpty {
      try visitor.visitSingularStringField(value: self.typeURL, fieldNumber: 1)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 2)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularBytesField(value: self.value, fieldNumber: 3)
    }
    if self.payloadVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.payloadVersion, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_OpaqueTypedPayload, rhs: Kaname_V1_OpaqueTypedPayload) -> Bool {
    if lhs.typeURL != rhs.typeURL {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.value != rhs.value {return false}
    if lhs.payloadVersion != rhs.payloadVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_EventProvenance: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EventProvenance"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}source_kind\0\u{3}provider_instance_id\0\u{3}native_type\0\u{3}native_cursor\0\u{3}raw_evidence_digest\0\u{3}retention_class\0\u{b}raw_payload\0\u{c}\u{7}\u{9}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sourceKind) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.providerInstanceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.nativeType) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.nativeCursor) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.rawEvidenceDigest) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.retentionClass) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sourceKind.isEmpty {
      try visitor.visitSingularStringField(value: self.sourceKind, fieldNumber: 1)
    }
    if !self.providerInstanceID.isEmpty {
      try visitor.visitSingularStringField(value: self.providerInstanceID, fieldNumber: 2)
    }
    if !self.nativeType.isEmpty {
      try visitor.visitSingularStringField(value: self.nativeType, fieldNumber: 3)
    }
    if !self.nativeCursor.isEmpty {
      try visitor.visitSingularBytesField(value: self.nativeCursor, fieldNumber: 4)
    }
    if !self.rawEvidenceDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.rawEvidenceDigest, fieldNumber: 5)
    }
    if self.retentionClass != .unspecified {
      try visitor.visitSingularEnumField(value: self.retentionClass, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_EventProvenance, rhs: Kaname_V1_EventProvenance) -> Bool {
    if lhs.sourceKind != rhs.sourceKind {return false}
    if lhs.providerInstanceID != rhs.providerInstanceID {return false}
    if lhs.nativeType != rhs.nativeType {return false}
    if lhs.nativeCursor != rhs.nativeCursor {return false}
    if lhs.rawEvidenceDigest != rhs.rawEvidenceDigest {return false}
    if lhs.retentionClass != rhs.retentionClass {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_Scope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Scope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}project_id\0\u{3}workspace_id\0\u{3}account_id\0\u{3}authority_id\0\u{3}egress_class\0\u{3}destination_digest\0\u{c}\u{7}\u{9}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.projectID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.workspaceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accountID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.authorityID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.egressClass) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.destinationDigest) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.projectID.isEmpty {
      try visitor.visitSingularStringField(value: self.projectID, fieldNumber: 1)
    }
    if !self.workspaceID.isEmpty {
      try visitor.visitSingularStringField(value: self.workspaceID, fieldNumber: 2)
    }
    if !self.accountID.isEmpty {
      try visitor.visitSingularStringField(value: self.accountID, fieldNumber: 3)
    }
    if !self.authorityID.isEmpty {
      try visitor.visitSingularStringField(value: self.authorityID, fieldNumber: 4)
    }
    if !self.egressClass.isEmpty {
      try visitor.visitSingularStringField(value: self.egressClass, fieldNumber: 5)
    }
    if !self.destinationDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.destinationDigest, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_Scope, rhs: Kaname_V1_Scope) -> Bool {
    if lhs.projectID != rhs.projectID {return false}
    if lhs.workspaceID != rhs.workspaceID {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.authorityID != rhs.authorityID {return false}
    if lhs.egressClass != rhs.egressClass {return false}
    if lhs.destinationDigest != rhs.destinationDigest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
