// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/sync.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Kaname_V1_DeviceEnrollmentState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case pending // = 1
  case active // = 2
  case rejected // = 3
  case revoked // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .pending
    case 2: self = .active
    case 3: self = .rejected
    case 4: self = .revoked
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .pending: return 1
    case .active: return 2
    case .rejected: return 3
    case .revoked: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_DeviceEnrollmentState] = [
    .unspecified,
    .pending,
    .active,
    .rejected,
    .revoked,
  ]

}

public nonisolated enum Kaname_V1_SyncReceiptState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case received // = 1
  case decrypted // = 2
  case policyAccepted // = 3
  case applied // = 4
  case rejected // = 5
  case resyncRequired // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .received
    case 2: self = .decrypted
    case 3: self = .policyAccepted
    case 4: self = .applied
    case 5: self = .rejected
    case 6: self = .resyncRequired
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .received: return 1
    case .decrypted: return 2
    case .policyAccepted: return 3
    case .applied: return 4
    case .rejected: return 5
    case .resyncRequired: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_SyncReceiptState] = [
    .unspecified,
    .received,
    .decrypted,
    .policyAccepted,
    .applied,
    .rejected,
    .resyncRequired,
  ]

}

/// Public device identity. Private key material never enters this protocol.
public nonisolated struct Kaname_V1_DevicePublicIdentity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var keyID: String = String()

  public var displayName: String = String()

  public var platform: String = String()

  public var hpkePublicKey: Data = Data()

  public var keyGeneration: UInt64 = 0

  public var createdAtUnixMillis: Int64 = 0

  public var expiresAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Enrollment is confirmed locally by Justin on both devices. The short
/// confirmation value itself is never stored or transported by Kaname.
public nonisolated struct Kaname_V1_DeviceEnrollmentChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var schemaVersion: Kaname_V1_SchemaVersion {
    get {_schemaVersion ?? Kaname_V1_SchemaVersion()}
    set {_schemaVersion = newValue}
  }
  /// Returns true if `schemaVersion` has been explicitly set.
  public var hasSchemaVersion: Bool {self._schemaVersion != nil}
  /// Clears the value of `schemaVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSchemaVersion() {self._schemaVersion = nil}

  public var enrollmentID: String = String()

  public var proposedDevice: Kaname_V1_DevicePublicIdentity {
    get {_proposedDevice ?? Kaname_V1_DevicePublicIdentity()}
    set {_proposedDevice = newValue}
  }
  /// Returns true if `proposedDevice` has been explicitly set.
  public var hasProposedDevice: Bool {self._proposedDevice != nil}
  /// Clears the value of `proposedDevice`. Subsequent reads from it will return its default value.
  public mutating func clearProposedDevice() {self._proposedDevice = nil}

  public var macNonce: Data = Data()

  public var confirmationDigest: Data = Data()

  public var expiresAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _schemaVersion: Kaname_V1_SchemaVersion? = nil
  fileprivate var _proposedDevice: Kaname_V1_DevicePublicIdentity? = nil
}

public nonisolated struct Kaname_V1_DeviceEnrollmentDecision: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enrollmentID: String = String()

  public var state: Kaname_V1_DeviceEnrollmentState = .unspecified

  public var macDeviceID: String = String()

  public var transcriptDigest: Data = Data()

  public var decidedAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_DeviceEnrollmentReceipt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enrollmentID: String = String()

  public var deviceID: String = String()

  public var state: Kaname_V1_DeviceEnrollmentState = .unspecified

  public var duplicate: Bool = false

  public var reasonCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_DeviceKeyRotation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var previousKeyID: String = String()

  public var nextIdentity: Kaname_V1_DevicePublicIdentity {
    get {_nextIdentity ?? Kaname_V1_DevicePublicIdentity()}
    set {_nextIdentity = newValue}
  }
  /// Returns true if `nextIdentity` has been explicitly set.
  public var hasNextIdentity: Bool {self._nextIdentity != nil}
  /// Clears the value of `nextIdentity`. Subsequent reads from it will return its default value.
  public mutating func clearNextIdentity() {self._nextIdentity = nil}

  public var transcriptDigest: Data = Data()

  public var rotatedAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _nextIdentity: Kaname_V1_DevicePublicIdentity? = nil
}

public nonisolated struct Kaname_V1_DeviceRevocation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var keyID: String = String()

  public var revokedAtUnixMillis: Int64 = 0

  public var reasonCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// This exact serialized header is used as HPKE authenticated data. Relays may
/// decode it for routing but cannot alter it without making decryption fail.
public nonisolated struct Kaname_V1_SyncAuthenticatedHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var schemaVersion: Kaname_V1_SchemaVersion {
    get {_schemaVersion ?? Kaname_V1_SchemaVersion()}
    set {_schemaVersion = newValue}
  }
  /// Returns true if `schemaVersion` has been explicitly set.
  public var hasSchemaVersion: Bool {self._schemaVersion != nil}
  /// Clears the value of `schemaVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSchemaVersion() {self._schemaVersion = nil}

  public var envelopeID: String = String()

  public var senderDeviceID: String = String()

  public var senderKeyID: String = String()

  public var recipientDeviceID: String = String()

  public var recipientKeyID: String = String()

  public var senderSequence: UInt64 = 0

  public var previousEnvelopeDigest: Data = Data()

  public var sentAtUnixMillis: Int64 = 0

  public var expiresAtUnixMillis: Int64 = 0

  public var payloadKind: String = String()

  public var plaintextDigest: Data = Data()

  public var contentType: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _schemaVersion: Kaname_V1_SchemaVersion? = nil
}

/// RFC 9180 authenticated HPKE using X25519, HKDF-SHA256, and ChaCha20-Poly1305.
/// authenticated_header is retained byte-for-byte and is never reconstructed
/// for integrity checks.
public nonisolated struct Kaname_V1_EncryptedSyncEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var authenticatedHeader: Data = Data()

  public var encapsulatedKey: Data = Data()

  public var ciphertext: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Kaname_V1_SyncReceipt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var envelopeID: String = String()

  public var senderDeviceID: String = String()

  public var senderSequence: UInt64 = 0

  public var state: Kaname_V1_SyncReceiptState = .unspecified

  public var reasonCode: String = String()

  public var macStorePosition: UInt64 = 0

  public var recordedAtUnixMillis: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_DeviceEnrollmentState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEVICE_ENROLLMENT_STATE_UNSPECIFIED\0\u{1}DEVICE_ENROLLMENT_STATE_PENDING\0\u{1}DEVICE_ENROLLMENT_STATE_ACTIVE\0\u{1}DEVICE_ENROLLMENT_STATE_REJECTED\0\u{1}DEVICE_ENROLLMENT_STATE_REVOKED\0")
}

nonisolated extension Kaname_V1_SyncReceiptState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SYNC_RECEIPT_STATE_UNSPECIFIED\0\u{1}SYNC_RECEIPT_STATE_RECEIVED\0\u{1}SYNC_RECEIPT_STATE_DECRYPTED\0\u{1}SYNC_RECEIPT_STATE_POLICY_ACCEPTED\0\u{1}SYNC_RECEIPT_STATE_APPLIED\0\u{1}SYNC_RECEIPT_STATE_REJECTED\0\u{1}SYNC_RECEIPT_STATE_RESYNC_REQUIRED\0")
}

nonisolated extension Kaname_V1_DevicePublicIdentity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DevicePublicIdentity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{3}key_id\0\u{3}display_name\0\u{1}platform\0\u{3}hpke_public_key\0\u{3}key_generation\0\u{3}created_at_unix_millis\0\u{3}expires_at_unix_millis\0\u{b}private_key\0\u{b}apns_token\0\u{c}\u{9}\u{17}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.keyID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.hpkePublicKey) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.keyGeneration) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.createdAtUnixMillis) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.expiresAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.keyID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyID, fieldNumber: 2)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 3)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 4)
    }
    if !self.hpkePublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.hpkePublicKey, fieldNumber: 5)
    }
    if self.keyGeneration != 0 {
      try visitor.visitSingularUInt64Field(value: self.keyGeneration, fieldNumber: 6)
    }
    if self.createdAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAtUnixMillis, fieldNumber: 7)
    }
    if self.expiresAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAtUnixMillis, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_DevicePublicIdentity, rhs: Kaname_V1_DevicePublicIdentity) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.hpkePublicKey != rhs.hpkePublicKey {return false}
    if lhs.keyGeneration != rhs.keyGeneration {return false}
    if lhs.createdAtUnixMillis != rhs.createdAtUnixMillis {return false}
    if lhs.expiresAtUnixMillis != rhs.expiresAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_DeviceEnrollmentChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceEnrollmentChallenge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schema_version\0\u{3}enrollment_id\0\u{3}proposed_device\0\u{3}mac_nonce\0\u{3}confirmation_digest\0\u{3}expires_at_unix_millis\0\u{b}confirmation_code\0\u{b}private_key\0\u{c}\u{7}\u{19}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._schemaVersion) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.enrollmentID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._proposedDevice) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.macNonce) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.confirmationDigest) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.expiresAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._schemaVersion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.enrollmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.enrollmentID, fieldNumber: 2)
    }
    try { if let v = self._proposedDevice {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.macNonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.macNonce, fieldNumber: 4)
    }
    if !self.confirmationDigest.isEmpty {
      try visitor.visitSingularBytesField(value: self.confirmationDigest, fieldNumber: 5)
    }
    if self.expiresAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAtUnixMillis, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_DeviceEnrollmentChallenge, rhs: Kaname_V1_DeviceEnrollmentChallenge) -> Bool {
    if lhs._schemaVersion != rhs._schemaVersion {return false}
    if lhs.enrollmentID != rhs.enrollmentID {return false}
    if lhs._proposedDevice != rhs._proposedDevice {return false}
    if lhs.macNonce != rhs.macNonce {return false}
    if lhs.confirmationDigest != rhs.confirmationDigest {return false}
    if lhs.expiresAtUnixMillis != rhs.expiresAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_DeviceEnrollmentDecision: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceEnrollmentDecision"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enrollment_id\0\u{1}state\0\u{3}mac_device_id\0\u{3}transcript_digest\0\u{3}decided_at_unix_millis\0\u{c}\u{6}\u{a}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.enrollmentID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.macDeviceID) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.transcriptDigest) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.decidedAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.enrollmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.enrollmentID, fieldNumber: 1)
    }
    if self.state != .unspecified {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 2)
    }
    if !self.macDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.macDeviceID, fieldNumber: 3)
    }
    if !self.transcriptDigest.isEmpty {
      try visitor.visitSingularBytesField(value: self.transcriptDigest, fieldNumber: 4)
    }
    if self.decidedAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.decidedAtUnixMillis, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_DeviceEnrollmentDecision, rhs: Kaname_V1_DeviceEnrollmentDecision) -> Bool {
    if lhs.enrollmentID != rhs.enrollmentID {return false}
    if lhs.state != rhs.state {return false}
    if lhs.macDeviceID != rhs.macDeviceID {return false}
    if lhs.transcriptDigest != rhs.transcriptDigest {return false}
    if lhs.decidedAtUnixMillis != rhs.decidedAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_DeviceEnrollmentReceipt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceEnrollmentReceipt"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enrollment_id\0\u{3}device_id\0\u{1}state\0\u{1}duplicate\0\u{3}reason_code\0\u{c}\u{6}\u{a}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.enrollmentID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.duplicate) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.enrollmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.enrollmentID, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if self.state != .unspecified {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 3)
    }
    if self.duplicate != false {
      try visitor.visitSingularBoolField(value: self.duplicate, fieldNumber: 4)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_DeviceEnrollmentReceipt, rhs: Kaname_V1_DeviceEnrollmentReceipt) -> Bool {
    if lhs.enrollmentID != rhs.enrollmentID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.state != rhs.state {return false}
    if lhs.duplicate != rhs.duplicate {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_DeviceKeyRotation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceKeyRotation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{3}previous_key_id\0\u{3}next_identity\0\u{3}transcript_digest\0\u{3}rotated_at_unix_millis\0\u{c}\u{6}\u{a}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.previousKeyID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._nextIdentity) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.transcriptDigest) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.rotatedAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.previousKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.previousKeyID, fieldNumber: 2)
    }
    try { if let v = self._nextIdentity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.transcriptDigest.isEmpty {
      try visitor.visitSingularBytesField(value: self.transcriptDigest, fieldNumber: 4)
    }
    if self.rotatedAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.rotatedAtUnixMillis, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_DeviceKeyRotation, rhs: Kaname_V1_DeviceKeyRotation) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.previousKeyID != rhs.previousKeyID {return false}
    if lhs._nextIdentity != rhs._nextIdentity {return false}
    if lhs.transcriptDigest != rhs.transcriptDigest {return false}
    if lhs.rotatedAtUnixMillis != rhs.rotatedAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_DeviceRevocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceRevocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{3}key_id\0\u{3}revoked_at_unix_millis\0\u{3}reason_code\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.keyID) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.revokedAtUnixMillis) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.keyID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyID, fieldNumber: 2)
    }
    if self.revokedAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.revokedAtUnixMillis, fieldNumber: 3)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_DeviceRevocation, rhs: Kaname_V1_DeviceRevocation) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.revokedAtUnixMillis != rhs.revokedAtUnixMillis {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_SyncAuthenticatedHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncAuthenticatedHeader"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schema_version\0\u{3}envelope_id\0\u{3}sender_device_id\0\u{3}sender_key_id\0\u{3}recipient_device_id\0\u{3}recipient_key_id\0\u{3}sender_sequence\0\u{3}previous_envelope_digest\0\u{3}sent_at_unix_millis\0\u{3}expires_at_unix_millis\0\u{3}payload_kind\0\u{3}plaintext_digest\0\u{3}content_type\0\u{b}plaintext\0\u{b}notification_preview\0\u{c}\u{e}\u{12}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._schemaVersion) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.envelopeID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.senderDeviceID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.senderKeyID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.recipientDeviceID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.recipientKeyID) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.senderSequence) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self.previousEnvelopeDigest) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.sentAtUnixMillis) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self.expiresAtUnixMillis) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.payloadKind) }()
      case 12: try { try decoder.decodeSingularBytesField(value: &self.plaintextDigest) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._schemaVersion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.envelopeID.isEmpty {
      try visitor.visitSingularStringField(value: self.envelopeID, fieldNumber: 2)
    }
    if !self.senderDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.senderDeviceID, fieldNumber: 3)
    }
    if !self.senderKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.senderKeyID, fieldNumber: 4)
    }
    if !self.recipientDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.recipientDeviceID, fieldNumber: 5)
    }
    if !self.recipientKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.recipientKeyID, fieldNumber: 6)
    }
    if self.senderSequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.senderSequence, fieldNumber: 7)
    }
    if !self.previousEnvelopeDigest.isEmpty {
      try visitor.visitSingularBytesField(value: self.previousEnvelopeDigest, fieldNumber: 8)
    }
    if self.sentAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.sentAtUnixMillis, fieldNumber: 9)
    }
    if self.expiresAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAtUnixMillis, fieldNumber: 10)
    }
    if !self.payloadKind.isEmpty {
      try visitor.visitSingularStringField(value: self.payloadKind, fieldNumber: 11)
    }
    if !self.plaintextDigest.isEmpty {
      try visitor.visitSingularBytesField(value: self.plaintextDigest, fieldNumber: 12)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_SyncAuthenticatedHeader, rhs: Kaname_V1_SyncAuthenticatedHeader) -> Bool {
    if lhs._schemaVersion != rhs._schemaVersion {return false}
    if lhs.envelopeID != rhs.envelopeID {return false}
    if lhs.senderDeviceID != rhs.senderDeviceID {return false}
    if lhs.senderKeyID != rhs.senderKeyID {return false}
    if lhs.recipientDeviceID != rhs.recipientDeviceID {return false}
    if lhs.recipientKeyID != rhs.recipientKeyID {return false}
    if lhs.senderSequence != rhs.senderSequence {return false}
    if lhs.previousEnvelopeDigest != rhs.previousEnvelopeDigest {return false}
    if lhs.sentAtUnixMillis != rhs.sentAtUnixMillis {return false}
    if lhs.expiresAtUnixMillis != rhs.expiresAtUnixMillis {return false}
    if lhs.payloadKind != rhs.payloadKind {return false}
    if lhs.plaintextDigest != rhs.plaintextDigest {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_EncryptedSyncEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EncryptedSyncEnvelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}authenticated_header\0\u{3}encapsulated_key\0\u{1}ciphertext\0\u{b}plaintext\0\u{b}private_key\0\u{b}shared_secret\0\u{c}\u{4}\u{c}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.authenticatedHeader) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.encapsulatedKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.authenticatedHeader.isEmpty {
      try visitor.visitSingularBytesField(value: self.authenticatedHeader, fieldNumber: 1)
    }
    if !self.encapsulatedKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.encapsulatedKey, fieldNumber: 2)
    }
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_EncryptedSyncEnvelope, rhs: Kaname_V1_EncryptedSyncEnvelope) -> Bool {
    if lhs.authenticatedHeader != rhs.authenticatedHeader {return false}
    if lhs.encapsulatedKey != rhs.encapsulatedKey {return false}
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_SyncReceipt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncReceipt"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}envelope_id\0\u{3}sender_device_id\0\u{3}sender_sequence\0\u{1}state\0\u{3}reason_code\0\u{3}mac_store_position\0\u{3}recorded_at_unix_millis\0\u{c}\u{8}\u{8}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.envelopeID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.senderDeviceID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.senderSequence) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.macStorePosition) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.recordedAtUnixMillis) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.envelopeID.isEmpty {
      try visitor.visitSingularStringField(value: self.envelopeID, fieldNumber: 1)
    }
    if !self.senderDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.senderDeviceID, fieldNumber: 2)
    }
    if self.senderSequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.senderSequence, fieldNumber: 3)
    }
    if self.state != .unspecified {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 4)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 5)
    }
    if self.macStorePosition != 0 {
      try visitor.visitSingularUInt64Field(value: self.macStorePosition, fieldNumber: 6)
    }
    if self.recordedAtUnixMillis != 0 {
      try visitor.visitSingularInt64Field(value: self.recordedAtUnixMillis, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_SyncReceipt, rhs: Kaname_V1_SyncReceipt) -> Bool {
    if lhs.envelopeID != rhs.envelopeID {return false}
    if lhs.senderDeviceID != rhs.senderDeviceID {return false}
    if lhs.senderSequence != rhs.senderSequence {return false}
    if lhs.state != rhs.state {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.macStorePosition != rhs.macStorePosition {return false}
    if lhs.recordedAtUnixMillis != rhs.recordedAtUnixMillis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
