// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kaname/v1/approval.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Kaname_V1_ApprovalDecision: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case approve // = 1
  case reject // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .approve
    case 2: self = .reject
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .approve: return 1
    case .reject: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Kaname_V1_ApprovalDecision] = [
    .unspecified,
    .approve,
    .reject,
  ]

}

public nonisolated struct Kaname_V1_ApprovalRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var approvalID: String {
    get {_storage._approvalID}
    set {_uniqueStorage()._approvalID = newValue}
  }

  public var actionKind: String {
    get {_storage._actionKind}
    set {_uniqueStorage()._actionKind = newValue}
  }

  public var scope: Kaname_V1_Scope {
    get {_storage._scope ?? Kaname_V1_Scope()}
    set {_uniqueStorage()._scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {_storage._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {_uniqueStorage()._scope = nil}

  public var targetID: String {
    get {_storage._targetID}
    set {_uniqueStorage()._targetID = newValue}
  }

  public var targetRevision: String {
    get {_storage._targetRevision}
    set {_uniqueStorage()._targetRevision = newValue}
  }

  public var effectDigest: Data {
    get {_storage._effectDigest}
    set {_uniqueStorage()._effectDigest = newValue}
  }

  public var consequence: String {
    get {_storage._consequence}
    set {_uniqueStorage()._consequence = newValue}
  }

  public var reversible: Bool {
    get {_storage._reversible}
    set {_uniqueStorage()._reversible = newValue}
  }

  public var expiresAtUnixMillis: Int64 {
    get {_storage._expiresAtUnixMillis}
    set {_uniqueStorage()._expiresAtUnixMillis = newValue}
  }

  public var policyReference: String {
    get {_storage._policyReference}
    set {_uniqueStorage()._policyReference = newValue}
  }

  public var fingerprint: Data {
    get {_storage._fingerprint}
    set {_uniqueStorage()._fingerprint = newValue}
  }

  public var approvalPayloadVersion: UInt32 {
    get {_storage._approvalPayloadVersion}
    set {_uniqueStorage()._approvalPayloadVersion = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Kaname_V1_ApprovalResolution: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var approvalID: String = String()

  public var decision: Kaname_V1_ApprovalDecision = .unspecified

  public var expectedFingerprint: Data = Data()

  public var actorID: String = String()

  public var deviceID: String = String()

  public var standingRuleReference: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "kaname.v1"

nonisolated extension Kaname_V1_ApprovalDecision: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0APPROVAL_DECISION_UNSPECIFIED\0\u{1}APPROVAL_DECISION_APPROVE\0\u{1}APPROVAL_DECISION_REJECT\0")
}

nonisolated extension Kaname_V1_ApprovalRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ApprovalRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}approval_id\0\u{3}action_kind\0\u{1}scope\0\u{3}target_id\0\u{3}target_revision\0\u{3}effect_digest\0\u{1}consequence\0\u{1}reversible\0\u{3}expires_at_unix_millis\0\u{3}policy_reference\0\u{1}fingerprint\0\u{3}approval_payload_version\0\u{b}recipient_address\0\u{b}approval_secret\0\u{c}\u{d}\u{13}")

  fileprivate class _StorageClass {
    var _approvalID: String = String()
    var _actionKind: String = String()
    var _scope: Kaname_V1_Scope? = nil
    var _targetID: String = String()
    var _targetRevision: String = String()
    var _effectDigest: Data = Data()
    var _consequence: String = String()
    var _reversible: Bool = false
    var _expiresAtUnixMillis: Int64 = 0
    var _policyReference: String = String()
    var _fingerprint: Data = Data()
    var _approvalPayloadVersion: UInt32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _approvalID = source._approvalID
      _actionKind = source._actionKind
      _scope = source._scope
      _targetID = source._targetID
      _targetRevision = source._targetRevision
      _effectDigest = source._effectDigest
      _consequence = source._consequence
      _reversible = source._reversible
      _expiresAtUnixMillis = source._expiresAtUnixMillis
      _policyReference = source._policyReference
      _fingerprint = source._fingerprint
      _approvalPayloadVersion = source._approvalPayloadVersion
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._approvalID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._actionKind) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._scope) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._targetID) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._targetRevision) }()
        case 6: try { try decoder.decodeSingularBytesField(value: &_storage._effectDigest) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._consequence) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._reversible) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._expiresAtUnixMillis) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._policyReference) }()
        case 11: try { try decoder.decodeSingularBytesField(value: &_storage._fingerprint) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._approvalPayloadVersion) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._approvalID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._approvalID, fieldNumber: 1)
      }
      if !_storage._actionKind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._actionKind, fieldNumber: 2)
      }
      try { if let v = _storage._scope {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._targetID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._targetID, fieldNumber: 4)
      }
      if !_storage._targetRevision.isEmpty {
        try visitor.visitSingularStringField(value: _storage._targetRevision, fieldNumber: 5)
      }
      if !_storage._effectDigest.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._effectDigest, fieldNumber: 6)
      }
      if !_storage._consequence.isEmpty {
        try visitor.visitSingularStringField(value: _storage._consequence, fieldNumber: 7)
      }
      if _storage._reversible != false {
        try visitor.visitSingularBoolField(value: _storage._reversible, fieldNumber: 8)
      }
      if _storage._expiresAtUnixMillis != 0 {
        try visitor.visitSingularInt64Field(value: _storage._expiresAtUnixMillis, fieldNumber: 9)
      }
      if !_storage._policyReference.isEmpty {
        try visitor.visitSingularStringField(value: _storage._policyReference, fieldNumber: 10)
      }
      if !_storage._fingerprint.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._fingerprint, fieldNumber: 11)
      }
      if _storage._approvalPayloadVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._approvalPayloadVersion, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_ApprovalRequest, rhs: Kaname_V1_ApprovalRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._approvalID != rhs_storage._approvalID {return false}
        if _storage._actionKind != rhs_storage._actionKind {return false}
        if _storage._scope != rhs_storage._scope {return false}
        if _storage._targetID != rhs_storage._targetID {return false}
        if _storage._targetRevision != rhs_storage._targetRevision {return false}
        if _storage._effectDigest != rhs_storage._effectDigest {return false}
        if _storage._consequence != rhs_storage._consequence {return false}
        if _storage._reversible != rhs_storage._reversible {return false}
        if _storage._expiresAtUnixMillis != rhs_storage._expiresAtUnixMillis {return false}
        if _storage._policyReference != rhs_storage._policyReference {return false}
        if _storage._fingerprint != rhs_storage._fingerprint {return false}
        if _storage._approvalPayloadVersion != rhs_storage._approvalPayloadVersion {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Kaname_V1_ApprovalResolution: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ApprovalResolution"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}approval_id\0\u{1}decision\0\u{3}expected_fingerprint\0\u{3}actor_id\0\u{3}device_id\0\u{3}standing_rule_reference\0\u{c}\u{7}\u{9}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.approvalID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.decision) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.expectedFingerprint) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.actorID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.standingRuleReference) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.approvalID.isEmpty {
      try visitor.visitSingularStringField(value: self.approvalID, fieldNumber: 1)
    }
    if self.decision != .unspecified {
      try visitor.visitSingularEnumField(value: self.decision, fieldNumber: 2)
    }
    if !self.expectedFingerprint.isEmpty {
      try visitor.visitSingularBytesField(value: self.expectedFingerprint, fieldNumber: 3)
    }
    if !self.actorID.isEmpty {
      try visitor.visitSingularStringField(value: self.actorID, fieldNumber: 4)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 5)
    }
    if !self.standingRuleReference.isEmpty {
      try visitor.visitSingularStringField(value: self.standingRuleReference, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Kaname_V1_ApprovalResolution, rhs: Kaname_V1_ApprovalResolution) -> Bool {
    if lhs.approvalID != rhs.approvalID {return false}
    if lhs.decision != rhs.decision {return false}
    if lhs.expectedFingerprint != rhs.expectedFingerprint {return false}
    if lhs.actorID != rhs.actorID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.standingRuleReference != rhs.standingRuleReference {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
