#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
TOKEN_PATH = ROOT / "DesignSystem" / "kaname.tokens.json"
OUTPUTS = {
    ROOT / "Sources" / "KanameDesignSystem" / "KanameGeneratedDesignValues.swift": "swift",
    ROOT / "Clients" / "KanameLink" / "Windows" / "App.xaml": "xaml",
    ROOT / "Clients" / "KanameLink" / "Linux" / "src" / "kaname-theme.css": "gtk",
}


def pascal(value: str) -> str:
    return value[:1].upper() + value[1:]


def number(value: int | float) -> str:
    return str(value) if isinstance(value, int) else format(value, ".12g")


def swift_source(document: dict[str, Any]) -> str:
    metadata = document["metadata"]
    nord = document["primitive"]["color"]["nord"]
    colors = document["semantic"]["color"]
    icons = document["semantic"]["icon"]
    statuses = document["semantic"]["status"]
    dimensions = document["dimension"]

    lines = [
        "// Synchronized from DesignSystem/kaname.tokens.json by",
        "// Scripts/generate-kaname-design-tokens.py. Review this projection with source changes.",
        "",
        "import Foundation",
        "",
        "public enum KanameDesignSystemMetadata {",
        f"    public static let schemaVersion = {metadata['schemaVersion']}",
        f"    public static let version = \"{metadata['version']}\"",
        "}",
        "",
        "enum KanameDesignGeneratedHex {",
        "    enum Nord {",
    ]
    lines.extend(f"        static let {key} = \"{value}\"" for key, value in nord.items())
    lines.extend(["    }", ""])
    for appearance in ("dark", "light"):
        lines.append(f"    enum {pascal(appearance)} {{")
        lines.extend(
            f"        static let {key} = \"{value}\""
            for key, value in colors[appearance].items()
        )
        lines.extend(["    }", ""])
    lines.extend(["}", "", "enum KanameDesignGeneratedDimension {"])
    for group, values in dimensions.items():
        lines.append(f"    enum {pascal(group)} {{")
        lines.extend(
            f"        static let {key}: Double = {number(value)}"
            for key, value in values.items()
        )
        lines.extend(["    }", ""])
    color_roles = list(dict.fromkeys(value["color"] for value in statuses.values()))
    lines.extend(["}", "", "enum KanameDesignGeneratedColorRole {"])
    lines.extend(f"    case {role}" for role in color_roles)
    lines.extend(["}", "", "enum KanameDesignGeneratedStatusKey {"])
    lines.extend(f"    case {key}" for key in statuses)
    lines.extend(["}", "", "enum KanameDesignGeneratedStatus {"])
    lines.extend([
        "    static func value(",
        "        for status: KanameDesignGeneratedStatusKey",
        "    ) -> (iconID: String, symbol: String, colorRole: KanameDesignGeneratedColorRole) {",
        "        switch status {",
    ])
    lines.extend(
        (
            f"        case .{key}: "
            f"(\"{value['icon']}\", \"{icons[value['icon']]['swiftUI']}\", .{value['color']})"
        )
        for key, value in statuses.items()
    )
    lines.extend(["        }", "    }"])
    lines.extend(["}", ""])
    return "\n".join(lines)


def xaml_brushes(colors: dict[str, str], indent: str = "          ") -> list[str]:
    return [
        f'{indent}<SolidColorBrush x:Key="Kaname{pascal(key)}Brush" Color="{value}" />'
        for key, value in colors.items()
    ]


def xaml_source(document: dict[str, Any]) -> str:
    colors = document["semantic"]["color"]
    icons = document["semantic"]["icon"]
    statuses = document["semantic"]["status"]
    dimensions = document["dimension"]
    high_contrast: dict[str, str] = {}
    for key in colors["dark"]:
        if key in {"selected", "accent", "accentStrong", "focus"}:
            high_contrast[key] = "{ThemeResource SystemColorHighlightColor}"
        elif key in {
            "separator", "textPrimary", "textSecondary", "textTertiary",
            "active", "success", "warning", "danger", "blocked", "external",
        }:
            high_contrast[key] = "{ThemeResource SystemColorWindowTextColor}"
        else:
            high_contrast[key] = "{ThemeResource SystemColorWindowColor}"

    lines = [
        "<!-- Generated by Scripts/generate-kaname-design-tokens.py. -->",
        "<!-- Do not edit this file directly; edit DesignSystem/kaname.tokens.json. -->",
        '<Application',
        '    x:Class="Cyberlane.KanameLink.App"',
        '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
        "  <Application.Resources>",
        "    <ResourceDictionary>",
        "      <ResourceDictionary.ThemeDictionaries>",
        '        <ResourceDictionary x:Key="Default">',
        *xaml_brushes(colors["dark"]),
        "        </ResourceDictionary>",
        '        <ResourceDictionary x:Key="Light">',
        *xaml_brushes(colors["light"]),
        "        </ResourceDictionary>",
        '        <ResourceDictionary x:Key="HighContrast">',
        *xaml_brushes(high_contrast),
        "        </ResourceDictionary>",
        "      </ResourceDictionary.ThemeDictionaries>",
    ]
    for key, value in statuses.items():
        icon = icons[value["icon"]]["winUI"]
        lines.append(f'      <x:String x:Key="KanameStatus{pascal(key)}Icon">{icon}</x:String>')
    for group, values in dimensions.items():
        for key, value in values.items():
            resource = f"Kaname{pascal(group)}{pascal(key)}"
            lines.append(f'      <x:Double x:Key="{resource}">{number(value)}</x:Double>')
    lines.extend([
        "    </ResourceDictionary>",
        "  </Application.Resources>",
        "</Application>",
        "",
    ])
    return "\n".join(lines)


def gtk_source(document: dict[str, Any]) -> str:
    dark = document["semantic"]["color"]["dark"]
    light = document["semantic"]["color"]["light"]
    icons = document["semantic"]["icon"]
    statuses = document["semantic"]["status"]
    lines = [
        "/* Generated by Scripts/generate-kaname-design-tokens.py. */",
        "/* Do not edit this file directly; edit DesignSystem/kaname.tokens.json. */",
    ]
    lines.extend(f"@define-color kaname_{key} {value.lower()};" for key, value in dark.items())
    lines.append("")
    lines.extend(f"@define-color kaname_light_{key} {value.lower()};" for key, value in light.items())
    lines.append("")
    for key, value in statuses.items():
        icon = icons[value["icon"]]["gtk"]
        lines.append(f'.kaname-status-{key}-icon {{ -gtk-icon-source: -gtk-icontheme("{icon}"); }}')
    lines.append("")
    return "\n".join(lines)


def render(document: dict[str, Any], kind: str) -> str:
    if kind == "swift":
        return swift_source(document)
    if kind == "xaml":
        return xaml_source(document)
    if kind == "gtk":
        return gtk_source(document)
    raise ValueError(kind)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Kaname platform token projections.")
    parser.add_argument("--check", action="store_true", help="Fail if generated projections are stale.")
    arguments = parser.parse_args()
    document = json.loads(TOKEN_PATH.read_text(encoding="utf-8"))
    failures: list[str] = []
    for path, kind in OUTPUTS.items():
        expected = render(document, kind)
        if arguments.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                failures.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if failures:
        for path in failures:
            print(f"error: stale generated design token projection: {path}", file=sys.stderr)
        return 1
    if arguments.check:
        print("Kaname generated design token projections are current.")
    else:
        print("Generated Kaname SwiftUI, WinUI, and GTK token projections.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
